Import('RTT_ROOT')
Import('rtconfig')
from building import *

if GetDepend('BOARD_USING_HYPERFLASH'):
    cwd = GetCurrentDir()
    src = Glob('*.c')
    CPPPATH = [cwd]

    if rtconfig.CROSS_TOOL == 'keil':
        LINKFLAGS  = '--keep=*(.boot_hdr.ivt)'
        LINKFLAGS += '--keep=*(.boot_hdr.boot_data)'
        LINKFLAGS += '--keep=*(.boot_hdr.dcd_data)'
        LINKFLAGS += '--keep=*(.boot_hdr.conf)'
    else:
        LINKFLAGS = '' 

    group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS) 
    Return('group') 

if GetDepend('BOARD_USING_QSPIFLASH'): 
    cwd = GetCurrentDir()
    src = Glob('*.c')

    CPPPATH = [cwd]

    if rtconfig.CROSS_TOOL == 'keil':
        LINKFLAGS  = '--keep=*(.boot_hdr.ivt)'
        LINKFLAGS += '--keep=*(.boot_hdr.boot_data)'
        LINKFLAGS += '--keep=*(.boot_hdr.dcd_data)'
        LINKFLAGS += '--keep=*(.boot_hdr.conf)'
    elif rtconfig.CROSS_TOOL == 'iar':
        LINKFLAGS  = ''
    else:
        LINKFLAGS = ''
    
    print LINKFLAGS
    group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = ['XIP_EXTERNAL_FLASH=1'], LINKFLAGS = LINKFLAGS)
    # group = []
    Return('group') 
